DEFAULT_PORT = 7772
DEFAULT_IP_ADDRESS = '127.0.0.1'
MAX_CONNECTIONS = 5
MAX_PACKAGE_SIZE = 1024
ENCODING = 'UTF-8'
ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'
GREETINGS = 'presense'
RESPONSE = 'response'
ERROR = 'error'
PORT_ARGV = '-p'
IP_ARGV = '-a'
GUEST = 'Guest'
MESSAGE = 'message'
MESSAGE_TEXT = 'mess_text'
SENDER = 'sender'
EXIT = 'exit'
DESTINATION = 'to'
RESPONSE_200 = {RESPONSE: 200}
RESPONSE_400 = {RESPONSE: 400,ERROR: None}
GET_CONTACTS = 'get_contacts'
LIST_INFO = 'data_list'
REMOVE_CONTACT = 'remove'
ADD_CONTACT = 'add'
USERS_REQUEST = 'get_users'
RESPONSE_202 = {RESPONSE: 202,LIST_INFO:None}